## You should change each of the following fields
## to customize your blog

title: Insights Unlocked - Data Analysis as the Key to Business Success
description: "A data science blog with a focus on business decision-making." 
author: Sofia Scribner
author_description: "I want to help you make data-driven decisions and gain insight into what the numbers really mean. My interests include marketing analytics, strategy, data visualization, predictive modeling, and consumer research."

url: https://sofiadscribner.github.io ## change this to https://yourusername.github.io
baseurl: /insights-unlocked-blog ## change this to the name of your blog repository
header_image: /assets/img/key.jpg ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github:  sofiadscribner
    twitter: 
    facebook: 
    email: 
    linkedin: sofia-scribner
    youtube: 
    tumblr: 
    website: 



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




